theme: jekyll-theme-cayman
title: Foley Lab
description: The Foley Research Lab

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

  # Icons
  rss: false
  email_address: # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket:
  dribbble:
  facebook:
  flickr:
  gitlab:
  github: "FoleyLab"
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "twitter"
  wordpress:
  youtube:
